# EXPERIMENT 2: NUMERICAL PYTHON (NUMPY)

#### Name: Arabelle Y. Villarin
#### Section: 2ECE-D‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎                            ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎  ‎ ‎ ‎ ‎ ‎‎ ‎  ‎ ‎ ‎ ‎ ‎ ‎ ‎ ‎ Date Submitted: September 3, 2024

In [138]:
import numpy as np

no. 1: NORMALIZATION PROBLEM

In [141]:
# Create an 5x5 array with random numbers from 0 to 1
X = np.random.rand(5,5) 

mean = X.mean() # Stores the mean from the X variable
std_dev = X.std() # Stores the standard deviation from the X variable

X_normalized = (X - mean) / std_dev # Calculate for the normalized X

print(X_normalized) # Print the normalized array of X

np.save('X_normalized.npy', X_normalized) # Save the normalized array in a file

[[ 1.47784465 -1.13575625 -0.81228136  0.41262897  1.5597271 ]
 [-0.8570012  -0.7856373  -0.48101047 -1.1101737  -1.40551183]
 [-1.24076345  0.02774222 -1.18793838 -0.04947423 -0.82820953]
 [-0.28640261  1.4306911   1.16926018  0.28587308  0.46886684]
 [ 1.58672653 -0.22553179 -0.52578946  1.12499696  1.38712391]]


no. 2: DIVISIBLE BY 3 PROBLEM

In [145]:
X = np.arange(1, 101) # Create an array from positive integer 1 to 100

X_squared = X ** 2 # Square all the numbers

X_reshape = X_squared.reshape(10, 10) # Make the array in a 10x10 form

div_by_3 = X_reshape[X_reshape % 3 == 0] # Use modulo to determine the elements divisible by 3

print(div_by_3) # Print all squared numbers from 1 to 100 that are divisible to 3

np.save('div_by_3.npy', div_by_3) # Save the array in a file

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
